import Head from 'next/head'
import Header from '../components/header'
import Signup from './signup'
import Login from './login'
import { useEffect, useState } from 'react'
//import axios from 'axios'



export default function home() {
    //const [user,setUser]=useState({ })
    //axios.defaults.withCredentials=true
//
    //const sendHttpRequest = async()=>{
    //  try{
    //    const res = await axios.get("http://localhost:3001/user/user")
    //    console.log(res)
    //  } catch (err){ console.error(err)}

    //}

    

    const sendHttpRequest =  async()=>{
        try{
            const res = await fetch("http://localhost:3001/user/user", {
              headers:{
                cookie:""
              },
              credentials: 'include',
            });
            const data = await res.json();
            console.log(data);
        } catch (err) {
          console.log(err)
        }
    }
    
    useEffect(()=>{
        sendHttpRequest();
    },[])

  return (
      <div>
        <Head>
          <title>Signup</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <Header />        
            <div>
                <h1 className='w-screen h-screen flex justify-center items-center'> Welcome </h1>
            </div>
        </main>

      </div>
  )
}